name: notif_app
description: notif app
version: 1.2.1
repository: https://github.com/bgoncharuck/notif_app
issue_tracker: https://github.com/bgoncharuck/notif_app/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: gabrimatic.info.restart
        pluginClass: RestartPlugin
      ios:
        pluginClass: SentryNotificationErrors
      web:
        pluginClass: RestartWeb
        fileName: restart_web.dart